//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSALib2 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSALib2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artefaktkontrolle ähnelt.
        /// </summary>
        internal static string ArtifactControl {
            get {
                return ResourceManager.GetString("ArtifactControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Astralenergie ähnelt.
        /// </summary>
        internal static string AstralEnergy {
            get {
                return ResourceManager.GetString("AstralEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP ähnelt.
        /// </summary>
        internal static string AstralEnergyShort {
            get {
                return ResourceManager.GetString("AstralEnergyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fernkampf-Basis ähnelt.
        /// </summary>
        internal static string BaseRange {
            get {
                return ResourceManager.GetString("BaseRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FK ähnelt.
        /// </summary>
        internal static string BaseRangeShort {
            get {
                return ResourceManager.GetString("BaseRangeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtsdatum ähnelt.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtstag ähnelt.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blocken-Basis ähnelt.
        /// </summary>
        internal static string BlockBasis {
            get {
                return ResourceManager.GetString("BlockBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BL ähnelt.
        /// </summary>
        internal static string BlockBasisShort {
            get {
                return ResourceManager.GetString("BlockBasisShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beherschungswert ähnelt.
        /// </summary>
        internal static string ControllValue {
            get {
                return ResourceManager.GetString("ControllValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BW ähnelt.
        /// </summary>
        internal static string ControllValueShort {
            get {
                return ResourceManager.GetString("ControllValueShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausdauer ähnelt.
        /// </summary>
        internal static string Endurance {
            get {
                return ResourceManager.GetString("Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AU ähnelt.
        /// </summary>
        internal static string EnduranceShort {
            get {
                return ResourceManager.GetString("EnduranceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Maximum wert des Charakters wurde überschritte ähnelt.
        /// </summary>
        internal static string ErrorAttrbutOverMax {
            get {
                return ResourceManager.GetString("ErrorAttrbutOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Gewählte Attribut exestiert bei diesem Charakter nicht ähnelt.
        /// </summary>
        internal static string ErrorAttributNotExist {
            get {
                return ResourceManager.GetString("ErrorAttributNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ErrorNullName {
            get {
                return ResourceManager.GetString("ErrorNullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versuch als Anforderung zweimal das gleiche Talent einzufügen&quot; ähnelt.
        /// </summary>
        internal static string ErrorTalentDobbleRequirement {
            get {
                return ResourceManager.GetString("ErrorTalentDobbleRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind nicht alle nötigen Variablen für das erstellen eines Talent gefüllt ähnelt.
        /// </summary>
        internal static string ErrorTalentMissingVariables {
            get {
                return ResourceManager.GetString("ErrorTalentMissingVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde Versucht Variablen in einem Talent Typen zu editieren in dem diese nicht vorhanden sind ähnelt.
        /// </summary>
        internal static string ErrorTalentUnknownTalentTypeEdit {
            get {
                return ResourceManager.GetString("ErrorTalentUnknownTalentTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Requirement Typ ähnelt.
        /// </summary>
        internal static string ErrorTalentUnknwonRequirement {
            get {
                return ResourceManager.GetString("ErrorTalentUnknwonRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Angegebene Talent Typ ist unbekannt ähnelt.
        /// </summary>
        internal static string ErrorUnknownTalentType {
            get {
                return ResourceManager.GetString("ErrorUnknownTalentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Charakter enthält einen Doppelten Namen bei den Values. Er kann nicht verwendet werden ähnelt.
        /// </summary>
        internal static string ErrorValueDobbleElement {
            get {
                return ResourceManager.GetString("ErrorValueDobbleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initiative-Basis ähnelt.
        /// </summary>
        internal static string InitiativeBasis {
            get {
                return ResourceManager.GetString("InitiativeBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INI ähnelt.
        /// </summary>
        internal static string InitiativeBasisShort {
            get {
                return ResourceManager.GetString("InitiativeBasisShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karma ähnelt.
        /// </summary>
        internal static string KarmaEnergy {
            get {
                return ResourceManager.GetString("KarmaEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karma Neutral ähnelt.
        /// </summary>
        internal static string KarmaEnergyNeutral {
            get {
                return ResourceManager.GetString("KarmaEnergyNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KEN ähnelt.
        /// </summary>
        internal static string KarmaEnergyNeutralShort {
            get {
                return ResourceManager.GetString("KarmaEnergyNeutralShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KE ähnelt.
        /// </summary>
        internal static string KarmaEnergyShort {
            get {
                return ResourceManager.GetString("KarmaEnergyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magieresistenz ähnelt.
        /// </summary>
        internal static string MagicResistance {
            get {
                return ResourceManager.GetString("MagicResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MR ähnelt.
        /// </summary>
        internal static string MagicResistanceShort {
            get {
                return ResourceManager.GetString("MagicResistanceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Padrade-Basis ähnelt.
        /// </summary>
        internal static string ParadeBase {
            get {
                return ResourceManager.GetString("ParadeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PA ähnelt.
        /// </summary>
        internal static string ParadeBaseShort {
            get {
                return ResourceManager.GetString("ParadeBaseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fernkampf-Basis ähnelt.
        /// </summary>
        internal static string RangeBase {
            get {
                return ResourceManager.GetString("RangeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FK ähnelt.
        /// </summary>
        internal static string RangeBaseShort {
            get {
                return ResourceManager.GetString("RangeBaseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entrückung ähnelt.
        /// </summary>
        internal static string Rapture {
            get {
                return ResourceManager.GetString("Rapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ER ähnelt.
        /// </summary>
        internal static string RaptureShort {
            get {
                return ResourceManager.GetString("RaptureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ruf ähnelt.
        /// </summary>
        internal static string Repute {
            get {
                return ResourceManager.GetString("Repute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit Luft ähnelt.
        /// </summary>
        internal static string SpeedAir {
            get {
                return ResourceManager.GetString("SpeedAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit ähnelt.
        /// </summary>
        internal static string SpeedLand {
            get {
                return ResourceManager.GetString("SpeedLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit Wasser ähnelt.
        /// </summary>
        internal static string SpeedWater {
            get {
                return ResourceManager.GetString("SpeedWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebensenergie ähnelt.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LE ähnelt.
        /// </summary>
        internal static string VitalityShort {
            get {
                return ResourceManager.GetString("VitalityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wundschwelle ähnelt.
        /// </summary>
        internal static string WoundSwell {
            get {
                return ResourceManager.GetString("WoundSwell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WS ähnelt.
        /// </summary>
        internal static string WoundSwellShort {
            get {
                return ResourceManager.GetString("WoundSwellShort", resourceCulture);
            }
        }
    }
}
