//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSALib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSALib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artefaktkontrolle ähnelt.
        /// </summary>
        internal static string ArtifactControl {
            get {
                return ResourceManager.GetString("ArtifactControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtsdatum ähnelt.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtstag ähnelt.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blocken-Basis ähnelt.
        /// </summary>
        internal static string BlockBasis {
            get {
                return ResourceManager.GetString("BlockBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Maximum wert des Charakters wurde überschritte ähnelt.
        /// </summary>
        internal static string ErrorAttrbutOverMax {
            get {
                return ResourceManager.GetString("ErrorAttrbutOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Gewählte Attribut exestiert bei diesem Charakter nicht ähnelt.
        /// </summary>
        internal static string ErrorAttributNotExist {
            get {
                return ResourceManager.GetString("ErrorAttributNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ErrorNullName {
            get {
                return ResourceManager.GetString("ErrorNullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versuch als Anforderung zweimal das gleiche Talent einzufügen&quot; ähnelt.
        /// </summary>
        internal static string ErrorTalentDobbleRequirement {
            get {
                return ResourceManager.GetString("ErrorTalentDobbleRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind nicht alle nötigen Variablen für das erstellen eines Talent gefüllt ähnelt.
        /// </summary>
        internal static string ErrorTalentMissingVariables {
            get {
                return ResourceManager.GetString("ErrorTalentMissingVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde Versucht Variablen in einem Talent Typen zu editieren in dem diese nicht vorhanden sind ähnelt.
        /// </summary>
        internal static string ErrorTalentUnknownTalentTypeEdit {
            get {
                return ResourceManager.GetString("ErrorTalentUnknownTalentTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Requirement Typ ähnelt.
        /// </summary>
        internal static string ErrorTalentUnknwonRequirement {
            get {
                return ResourceManager.GetString("ErrorTalentUnknwonRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Angegebene Talent Typ ist unbekannt ähnelt.
        /// </summary>
        internal static string ErrorUnknownTalentType {
            get {
                return ResourceManager.GetString("ErrorUnknownTalentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Charakter enthält einen Doppelten Namen bei den Values. Er kann nicht verwendet werden ähnelt.
        /// </summary>
        internal static string ErrorValueDobbleElement {
            get {
                return ResourceManager.GetString("ErrorValueDobbleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebensenergie ähnelt.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
    }
}
